version: '3.4'

services:
  deno:
    container_name: deno
    depends_on: 
      - db
    build:
      context: ./app
      dockerfile: ../deno.dockerfile
    ports:
      - "3000:3000"
    networks:
      - denoapp-network
    healthcheck:
      test: ["CMD", "curl", http://localhost:3000/beers"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      #- ./var/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: deno
      POSTGRES_DB: deno_beers
    networks:
      - denoapp-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deno -d deno_beers"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  denoapp-network:
    driver: bridge
